#
# .NET Core Test for ParallelEnvs
#

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetInstallVersion: '2.2.300'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: $(dotnetInstallVersion)
  displayName: 'dotnet Install'
- script: |
    dotnet --version
  displayName: 'dotnet Version'
- script: |
    dotnet build
  displayName: 'ParallelEnvs Build'
  workingDirectory: './vs/ParallelEnvsSystem/'
- script: |
    dotnet build
  displayName: 'ParallelEnvs CUI tool Build'
  workingDirectory: './vs/ParallelEnvsCUI/'
- script: |
    dotnet test --logger trx
  displayName: 'xUnit Test'
  workingDirectory: './vs/ParallelEnvsTest/'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish the test results'
