#
# .NET Core Test for ParallelEnvs
#

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  testProjectPath: ''
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'
- script: |
    dotnet --version
  displayName: 'DotNet Version'
- script: |
    dotnet build
  displayName: 'ParallelEnvs Build'
  workingDirectory: './vs/ParallelEnvsSystem/'
- script: |
    dotnet build
  displayName: 'ParallelEnvs CUI tool Build'
  workingDirectory: './vs/ParallelEnvsCUI/'
- script: |
    dotnet test
  displayName: 'xUnit Test'
  workingDirectory: './vs/ParallelEnvsTest/'
